### ISSUE TITLE
Add CSS variables support

### ISSUE THREAD

**Issue by luizbills** [luizbills/css-generator.php#2]

**Comment by luizbills** [comment]
Maybe something like:

```php
use luizbills\CSS_Generator\Generator as CSS_Generator;

$css = new CSS_Generator();

$css->add_variable( 'red', '#f00' );

$css->add_rule( '.color-red', [ 'color' => 'var(--red)' ] );
```

Expected:
```css
:root {
    --red: #f00;
}
.color-red {
    color: var(--red)
}
```

**Comment by luizbills** [comment]
Don't forget to trim whitespace surrounding CSS Custom Properties values.

The code below
```php
$css->add_variable( 'foo', '  red    ' );
```

Should results in
```css
:root {
    --foo: red;
}
```

Details: https://github.com/w3c/csswg-drafts/issues/774
